# SERVER
server:
  port: 8080

# DATABASE
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format-sql: true
    show-sql: false

# TEMPLATE
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true

# AVATAR
user-avatar:
  path: src/main/resources/user_avatar